/* automatically generated by rust-bindgen 0.69.4 */

pub type __u16 = ::aya_ebpf::cty::c_ushort;
pub type __be16 = __u16;
pub type __sum16 = __u16;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ethhdr {
    pub h_dest: [::aya_ebpf::cty::c_uchar; 6usize],
    pub h_source: [::aya_ebpf::cty::c_uchar; 6usize],
    pub h_proto: __be16,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct udphdr {
    pub source: __be16,
    pub dest: __be16,
    pub len: __be16,
    pub check: __sum16,
}
